package com.myspace.islamiccarmurabaha;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PR implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Car price")
	private java.lang.Double carPrice;
	@org.kie.api.definition.type.Label("Invoice number")
	private java.lang.Integer invoiceNumber;
	@org.kie.api.definition.type.Label("Car type")
	private java.lang.String carType;
	@org.kie.api.definition.type.Label("Chassis number")
	private java.lang.Integer chassisNumber;
	@org.kie.api.definition.type.Label("Car color")
	private java.lang.String carColor;
	@org.kie.api.definition.type.Label("Engine capacity")
	private java.lang.Double engineCapacity;
	@org.kie.api.definition.type.Label("Assignment")
	private java.lang.String assignment;

	public PR() {
	}

	public java.lang.Double getCarPrice() {
		return this.carPrice;
	}

	public void setCarPrice(java.lang.Double carPrice) {
		this.carPrice = carPrice;
	}

	public java.lang.Integer getInvoiceNumber() {
		return this.invoiceNumber;
	}

	public void setInvoiceNumber(java.lang.Integer invoiceNumber) {
		this.invoiceNumber = invoiceNumber;
	}

	public java.lang.String getCarType() {
		return this.carType;
	}

	public void setCarType(java.lang.String carType) {
		this.carType = carType;
	}

	public java.lang.Integer getChassisNumber() {
		return this.chassisNumber;
	}

	public void setChassisNumber(java.lang.Integer chassisNumber) {
		this.chassisNumber = chassisNumber;
	}

	public java.lang.String getCarColor() {
		return this.carColor;
	}

	public void setCarColor(java.lang.String carColor) {
		this.carColor = carColor;
	}

	public java.lang.Double getEngineCapacity() {
		return this.engineCapacity;
	}

	public void setEngineCapacity(java.lang.Double engineCapacity) {
		this.engineCapacity = engineCapacity;
	}

	public java.lang.String getAssignment() {
		return this.assignment;
	}

	public void setAssignment(java.lang.String assignment) {
		this.assignment = assignment;
	}

	public PR(java.lang.Double carPrice, java.lang.Integer invoiceNumber,
			java.lang.String carType, java.lang.Integer chassisNumber,
			java.lang.String carColor, java.lang.Double engineCapacity,
			java.lang.String assignment) {
		this.carPrice = carPrice;
		this.invoiceNumber = invoiceNumber;
		this.carType = carType;
		this.chassisNumber = chassisNumber;
		this.carColor = carColor;
		this.engineCapacity = engineCapacity;
		this.assignment = assignment;
	}

}